/**:
  ros__parameters:
    tracker_ignore_label:
      UNKNOWN : true
      CAR : false
      TRUCK : false
      BUS : true
      TRAILER : false
      MOTORCYCLE : false
      BICYCLE : false
      PEDESTRIAN : false
